# -*- coding: utf-8 -*-
"""240329

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUMA_0l7jJLYvafeh-NM2MFo4WkLv1C_
"""

minutes = int(input("분을 입력하세요: "))

hours = minutes // 60
remaining_minutes = minutes % 60

print("{:d} -> {:d}시간 {:d}분".format(minutes, hours, remaining_minutes))

C = float(input("섭씨 온도를 입력하세요: "))

F = (C * 1.8) + 32

print("섭씨 %d 도는 화씨 %.1f 도입니다." % (C, F))

r = int(input("원의 반지름을 입력하세요: "))

pi = 3.14

circumference = 2 * pi * r

area = pi * r ** 2

print("반지름이 {}인 원의 둘레는 {}이고, 면적은 {}입니다.".format(r,circumference,area))